version: "3.8"
   
services:
  backend:
    build: .
    image: b_comp
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    image: f_comp
    ports:
      - "8080:80"
    depends_on:
      - backend
