version: "3.8"
   
services:
  backend:
    build: .
    image: backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
