# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Push docker images to Dockerhub

on:
  push:
    branches: master
    tags:
      - "v*.*.*"
      - "paper**"

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set output
        id: vars
        run:
          TAG=$(echo $GITHUB_REF#refs/*/ | sed -e 's?/?-?g')
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push latest QuantumTranspiler Backend
        if: ${{ steps.vars.outputs.tag == 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: planqk/quantum-transpiler-backend:latest
      - name: Build and push version of QuantumTranspiler Backend
        if: ${{ steps.vars.outputs.tag != 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: planqk/quantum-transpiler-backend:${{ steps.vars.outputs.tag }}

      - name: Build and push latest QuantumTranspiler Frontend
        if: ${{ steps.vars.outputs.tag == 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/
          file: ./frontend/Dockerfile
          push: true
          tags: planqk/quantum-transpiler-frontend:latest
      - name: Build and push version of QuantumTranspiler Frontend
        if: ${{ steps.vars.outputs.tag != 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/
          file: ./frontend/Dockerfile
          push: true
          tags: planqk/quantum-transpiler-frontend:${{ steps.vars.outputs.tag }}
